-- 新增韋伯氏硬度（HW）欄位至出貨檢驗數據資料表
-- 對應安泰廠商的韋伯氏硬度(HW)檢驗項目

ALTER TABLE "出貨檢驗數據" ADD COLUMN IF NOT EXISTS "韋伯氏硬度1"  VARCHAR;
ALTER TABLE "出貨檢驗數據" ADD COLUMN IF NOT EXISTS "韋伯氏硬度2"  VARCHAR;
ALTER TABLE "出貨檢驗數據" ADD COLUMN IF NOT EXISTS "韋伯氏硬度3"  VARCHAR;
ALTER TABLE "出貨檢驗數據" ADD COLUMN IF NOT EXISTS "韋伯氏硬度4"  VARCHAR;
ALTER TABLE "出貨檢驗數據" ADD COLUMN IF NOT EXISTS "韋伯氏硬度5"  VARCHAR;
ALTER TABLE "出貨檢驗數據" ADD COLUMN IF NOT EXISTS "韋伯氏硬度6"  VARCHAR;
ALTER TABLE "出貨檢驗數據" ADD COLUMN IF NOT EXISTS "韋伯氏硬度7"  VARCHAR;
ALTER TABLE "出貨檢驗數據" ADD COLUMN IF NOT EXISTS "韋伯氏硬度8"  VARCHAR;
ALTER TABLE "出貨檢驗數據" ADD COLUMN IF NOT EXISTS "韋伯氏硬度9"  VARCHAR;
ALTER TABLE "出貨檢驗數據" ADD COLUMN IF NOT EXISTS "韋伯氏硬度10" VARCHAR;
