-- 量測點排除（不列入計算）：TUS/SAT 各加「已排除」旗標與原因
ALTER TABLE "TUS量測點明細"
    ADD COLUMN IF NOT EXISTS "已排除" BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "排除原因" TEXT;

ALTER TABLE "SAT量測點明細"
    ADD COLUMN IF NOT EXISTS "已排除" BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS "排除原因" TEXT;
