/**
 * 安裝 git pre-commit hook，自動執行 lint-staged-new.mjs
 */
import { execSync } from 'child_process';
import { writeFileSync, chmodSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const HOOK_DIR = resolve(ROOT, '.git', 'hooks');
const HOOK_PATH = resolve(HOOK_DIR, 'pre-commit');

const hookContent = `#!/bin/sh
# Auto-generated by scripts/setup-hooks.mjs
node scripts/lint-staged-new.mjs
`;

try {
  writeFileSync(HOOK_PATH, hookContent, { encoding: 'utf-8' });
  chmodSync(HOOK_PATH, 0o755);
  console.log('✅ pre-commit hook 已安裝：.git/hooks/pre-commit');
} catch (e) {
  console.error('❌ 安裝失敗：', e.message);
  console.log('請手動建立 .git/hooks/pre-commit 並貼上以下內容：');
  console.log(hookContent);
}
